DROP TABLE IF EXISTS `country`;

CREATE TABLE IF NOT EXISTS `country` (
  `iso` char(2) NOT NULL DEFAULT '',
  `name` varchar(255) NOT NULL DEFAULT '',
  `code` smallint(6) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY `code` (`code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


--
-- Country code
-- 

INSERT IGNORE INTO `country` VALUES ('af', 'Afghanistan', 4);
INSERT IGNORE INTO `country` VALUES ('ax', 'Aland Islands', 248);
INSERT IGNORE INTO `country` VALUES ('al', 'Albania', 8);
INSERT IGNORE INTO `country` VALUES ('dz', 'Algeria', 12);
INSERT IGNORE INTO `country` VALUES ('as', 'American Samoa', 16);
INSERT IGNORE INTO `country` VALUES ('ad', 'Andorra', 20);
INSERT IGNORE INTO `country` VALUES ('ao', 'Angola', 24);
INSERT IGNORE INTO `country` VALUES ('ai', 'Anguilla', 660);
INSERT IGNORE INTO `country` VALUES ('aq', 'Antarctica', 10);
INSERT IGNORE INTO `country` VALUES ('ag', 'Antigua and Barbuda', 28);
INSERT IGNORE INTO `country` VALUES ('ar', 'Argentina', 32);
INSERT IGNORE INTO `country` VALUES ('am', 'Armenia', 51);
INSERT IGNORE INTO `country` VALUES ('aw', 'Aruba', 533);
INSERT IGNORE INTO `country` VALUES ('au', 'Australia', 36);
INSERT IGNORE INTO `country` VALUES ('at', 'Austria', 40);
INSERT IGNORE INTO `country` VALUES ('az', 'Azerbaijan', 31);
INSERT IGNORE INTO `country` VALUES ('bs', 'Bahamas', 44);
INSERT IGNORE INTO `country` VALUES ('bh', 'Bahrain', 48);
INSERT IGNORE INTO `country` VALUES ('bd', 'Bangladesh', 50);
INSERT IGNORE INTO `country` VALUES ('bb', 'Barbados', 52);
INSERT IGNORE INTO `country` VALUES ('by', 'Belarus', 112);
INSERT IGNORE INTO `country` VALUES ('be', 'Belgium', 56);
INSERT IGNORE INTO `country` VALUES ('bz', 'Belize', 84);
INSERT IGNORE INTO `country` VALUES ('bj', 'Benin', 204);
INSERT IGNORE INTO `country` VALUES ('bm', 'Bermuda', 60);
INSERT IGNORE INTO `country` VALUES ('bt', 'Bhutan', 64);
INSERT IGNORE INTO `country` VALUES ('bo', 'Bolivia', 68);
INSERT IGNORE INTO `country` VALUES ('ba', 'Bosnia and Herzegovina', 70);
INSERT IGNORE INTO `country` VALUES ('bw', 'Botswana', 72);
INSERT IGNORE INTO `country` VALUES ('bv', 'Bouvet Island', 74);
INSERT IGNORE INTO `country` VALUES ('br', 'Brazil', 76);
INSERT IGNORE INTO `country` VALUES ('io', 'British Indian Ocean Territory', 86);
INSERT IGNORE INTO `country` VALUES ('bn', 'Brunei Darussalam', 96);
INSERT IGNORE INTO `country` VALUES ('bg', 'Bulgaria', 100);
INSERT IGNORE INTO `country` VALUES ('bf', 'Burkina Faso', 854);
INSERT IGNORE INTO `country` VALUES ('bi', 'Burundi', 108);
INSERT IGNORE INTO `country` VALUES ('kh', 'Cambodia', 116);
INSERT IGNORE INTO `country` VALUES ('cm', 'Cameroon', 120);
INSERT IGNORE INTO `country` VALUES ('ca', 'Canada', 124);
INSERT IGNORE INTO `country` VALUES ('cv', 'Cape Verde', 132);
INSERT IGNORE INTO `country` VALUES ('ky', 'Cayman Islands', 136);
INSERT IGNORE INTO `country` VALUES ('cf', 'Central African Republic', 140);
INSERT IGNORE INTO `country` VALUES ('td', 'Chad', 148);
INSERT IGNORE INTO `country` VALUES ('cl', 'Chile', 152);
INSERT IGNORE INTO `country` VALUES ('cn', 'China', 156);
INSERT IGNORE INTO `country` VALUES ('cx', 'Christmas Island', 162);
INSERT IGNORE INTO `country` VALUES ('cc', 'Cocos (Keeling) Islands', 166);
INSERT IGNORE INTO `country` VALUES ('co', 'Colombia', 170);
INSERT IGNORE INTO `country` VALUES ('km', 'Comoros', 174);
INSERT IGNORE INTO `country` VALUES ('cg', 'Congo', 178);
INSERT IGNORE INTO `country` VALUES ('cd', 'Congo, the Democratic Republic of the', 180);
INSERT IGNORE INTO `country` VALUES ('ck', 'Cook Islands', 184);
INSERT IGNORE INTO `country` VALUES ('cr', 'Costa Rica', 188);
INSERT IGNORE INTO `country` VALUES ('ci', 'Cote D''Ivoire', 384);
INSERT IGNORE INTO `country` VALUES ('hr', 'Croatia', 191);
INSERT IGNORE INTO `country` VALUES ('cu', 'Cuba', 192);
INSERT IGNORE INTO `country` VALUES ('cy', 'Cyprus', 196);
INSERT IGNORE INTO `country` VALUES ('cz', 'Czech Republic', 203);
INSERT IGNORE INTO `country` VALUES ('dk', 'Denmark', 208);
INSERT IGNORE INTO `country` VALUES ('dj', 'Djibouti', 262);
INSERT IGNORE INTO `country` VALUES ('dm', 'Dominica', 212);
INSERT IGNORE INTO `country` VALUES ('do', 'Dominican Republic', 214);
INSERT IGNORE INTO `country` VALUES ('ec', 'Ecuador', 218);
INSERT IGNORE INTO `country` VALUES ('eg', 'Egypt', 818);
INSERT IGNORE INTO `country` VALUES ('sv', 'El Salvador', 222);
INSERT IGNORE INTO `country` VALUES ('gq', 'Equatorial Guinea', 226);
INSERT IGNORE INTO `country` VALUES ('er', 'Eritrea', 232);
INSERT IGNORE INTO `country` VALUES ('ee', 'Estonia', 233);
INSERT IGNORE INTO `country` VALUES ('et', 'Ethiopia', 231);
INSERT IGNORE INTO `country` VALUES ('fk', 'Falkland Islands (Malvinas)', 238);
INSERT IGNORE INTO `country` VALUES ('fo', 'Faroe Islands', 234);
INSERT IGNORE INTO `country` VALUES ('fj', 'Fiji', 242);
INSERT IGNORE INTO `country` VALUES ('fi', 'Finland', 246);
INSERT IGNORE INTO `country` VALUES ('fr', 'France', 250);
INSERT IGNORE INTO `country` VALUES ('gf', 'French Guiana', 254);
INSERT IGNORE INTO `country` VALUES ('pf', 'French Polynesia', 258);
INSERT IGNORE INTO `country` VALUES ('tf', 'French Southern Territories', 260);
INSERT IGNORE INTO `country` VALUES ('ga', 'Gabon', 266);
INSERT IGNORE INTO `country` VALUES ('gm', 'Gambia', 270);
INSERT IGNORE INTO `country` VALUES ('ge', 'Georgia', 268);
INSERT IGNORE INTO `country` VALUES ('de', 'Germany', 276);
INSERT IGNORE INTO `country` VALUES ('gh', 'Ghana', 288);
INSERT IGNORE INTO `country` VALUES ('gi', 'Gibraltar', 292);
INSERT IGNORE INTO `country` VALUES ('gr', 'Greece', 300);
INSERT IGNORE INTO `country` VALUES ('gl', 'Greenland', 304);
INSERT IGNORE INTO `country` VALUES ('gd', 'Grenada', 308);
INSERT IGNORE INTO `country` VALUES ('gp', 'Guadeloupe', 312);
INSERT IGNORE INTO `country` VALUES ('gu', 'Guam', 316);
INSERT IGNORE INTO `country` VALUES ('gt', 'Guatemala', 320);
INSERT IGNORE INTO `country` VALUES ('gg', 'Guernsey', 831);
INSERT IGNORE INTO `country` VALUES ('gn', 'Guinea', 324);
INSERT IGNORE INTO `country` VALUES ('gw', 'Guinea-Bissau', 624);
INSERT IGNORE INTO `country` VALUES ('gy', 'Guyana', 328);
INSERT IGNORE INTO `country` VALUES ('ht', 'Haiti', 332);
INSERT IGNORE INTO `country` VALUES ('hm', 'Heard Island and Mcdonald Islands', 334);
INSERT IGNORE INTO `country` VALUES ('va', 'Holy See (Vatican City State)', 336);
INSERT IGNORE INTO `country` VALUES ('hn', 'Honduras', 340);
INSERT IGNORE INTO `country` VALUES ('hk', 'Hong Kong', 344);
INSERT IGNORE INTO `country` VALUES ('hu', 'Hungary', 348);
INSERT IGNORE INTO `country` VALUES ('is', 'Iceland', 352);
INSERT IGNORE INTO `country` VALUES ('in', 'India', 356);
INSERT IGNORE INTO `country` VALUES ('id', 'Indonesia', 360);
INSERT IGNORE INTO `country` VALUES ('ir', 'Iran, Islamic Republic of', 364);
INSERT IGNORE INTO `country` VALUES ('iq', 'Iraq', 368);
INSERT IGNORE INTO `country` VALUES ('ie', 'Ireland', 372);
INSERT IGNORE INTO `country` VALUES ('il', 'Israel', 376);
INSERT IGNORE INTO `country` VALUES ('it', 'Italy', 380);
INSERT IGNORE INTO `country` VALUES ('jm', 'Jamaica', 388);
INSERT IGNORE INTO `country` VALUES ('jp', 'Japan', 392);
INSERT IGNORE INTO `country` VALUES ('je', 'Jersey', 832);
INSERT IGNORE INTO `country` VALUES ('jo', 'Jordan', 400);
INSERT IGNORE INTO `country` VALUES ('kz', 'Kazakhstan', 398);
INSERT IGNORE INTO `country` VALUES ('ke', 'Kenya', 404);
INSERT IGNORE INTO `country` VALUES ('ki', 'Kiribati', 296);
INSERT IGNORE INTO `country` VALUES ('kp', 'Korea, Democratic People''s Republic of', 408);
INSERT IGNORE INTO `country` VALUES ('kr', 'Korea, Republic of', 410);
INSERT IGNORE INTO `country` VALUES ('kw', 'Kuwait', 414);
INSERT IGNORE INTO `country` VALUES ('kg', 'Kyrgyzstan', 417);
INSERT IGNORE INTO `country` VALUES ('la', 'Lao People''s Democratic Republic', 418);
INSERT IGNORE INTO `country` VALUES ('lv', 'Latvia', 428);
INSERT IGNORE INTO `country` VALUES ('lb', 'Lebanon', 422);
INSERT IGNORE INTO `country` VALUES ('ls', 'Lesotho', 426);
INSERT IGNORE INTO `country` VALUES ('lr', 'Liberia', 430);
INSERT IGNORE INTO `country` VALUES ('ly', 'Libyan Arab Jamahiriya', 434);
INSERT IGNORE INTO `country` VALUES ('li', 'Liechtenstein', 438);
INSERT IGNORE INTO `country` VALUES ('lt', 'Lithuania', 440);
INSERT IGNORE INTO `country` VALUES ('lu', 'Luxembourg', 442);
INSERT IGNORE INTO `country` VALUES ('mo', 'Macao', 446);
INSERT IGNORE INTO `country` VALUES ('mk', 'Macedonia, the Former Yugoslav Republic of', 807);
INSERT IGNORE INTO `country` VALUES ('mg', 'Madagascar', 450);
INSERT IGNORE INTO `country` VALUES ('mw', 'Malawi', 454);
INSERT IGNORE INTO `country` VALUES ('my', 'Malaysia', 458);
INSERT IGNORE INTO `country` VALUES ('mv', 'Maldives', 462);
INSERT IGNORE INTO `country` VALUES ('ml', 'Mali', 466);
INSERT IGNORE INTO `country` VALUES ('mt', 'Malta', 470);
INSERT IGNORE INTO `country` VALUES ('mh', 'Marshall Islands', 584);
INSERT IGNORE INTO `country` VALUES ('mq', 'Martinique', 474);
INSERT IGNORE INTO `country` VALUES ('mr', 'Mauritania', 478);
INSERT IGNORE INTO `country` VALUES ('mu', 'Mauritius', 480);
INSERT IGNORE INTO `country` VALUES ('yt', 'Mayotte', 175);
INSERT IGNORE INTO `country` VALUES ('mx', 'Mexico', 484);
INSERT IGNORE INTO `country` VALUES ('fm', 'Micronesia, Federated States of', 583);
INSERT IGNORE INTO `country` VALUES ('md', 'Moldova, Republic of', 498);
INSERT IGNORE INTO `country` VALUES ('mc', 'Monaco', 492);
INSERT IGNORE INTO `country` VALUES ('mn', 'Mongolia', 496);
INSERT IGNORE INTO `country` VALUES ('me', 'Montenegro', 499);
INSERT IGNORE INTO `country` VALUES ('me', 'Montenegro', 499);
INSERT IGNORE INTO `country` VALUES ('ms', 'Montserrat', 500);
INSERT IGNORE INTO `country` VALUES ('ma', 'Morocco', 504);
INSERT IGNORE INTO `country` VALUES ('mz', 'Mozambique', 508);
INSERT IGNORE INTO `country` VALUES ('mm', 'Myanmar', 104);
INSERT IGNORE INTO `country` VALUES ('na', 'Namibia', 516);
INSERT IGNORE INTO `country` VALUES ('nr', 'Nauru', 520);
INSERT IGNORE INTO `country` VALUES ('np', 'Nepal', 524);
INSERT IGNORE INTO `country` VALUES ('nl', 'Netherlands', 528);
INSERT IGNORE INTO `country` VALUES ('an', 'Netherlands Antilles', 530);
INSERT IGNORE INTO `country` VALUES ('nc', 'New Caledonia', 540);
INSERT IGNORE INTO `country` VALUES ('nz', 'New Zealand', 554);
INSERT IGNORE INTO `country` VALUES ('ni', 'Nicaragua', 558);
INSERT IGNORE INTO `country` VALUES ('ne', 'Niger', 562);
INSERT IGNORE INTO `country` VALUES ('ng', 'Nigeria', 566);
INSERT IGNORE INTO `country` VALUES ('nu', 'Niue', 570);
INSERT IGNORE INTO `country` VALUES ('nf', 'Norfolk Island', 574);
INSERT IGNORE INTO `country` VALUES ('mp', 'Northern Mariana Islands', 580);
INSERT IGNORE INTO `country` VALUES ('no', 'Norway', 578);
INSERT IGNORE INTO `country` VALUES ('om', 'Oman', 512);
INSERT IGNORE INTO `country` VALUES ('pk', 'Pakistan', 586);
INSERT IGNORE INTO `country` VALUES ('pw', 'Palau', 585);
INSERT IGNORE INTO `country` VALUES ('ps', 'Palestinian Territory, Occupied', 275);
INSERT IGNORE INTO `country` VALUES ('pa', 'Panama', 591);
INSERT IGNORE INTO `country` VALUES ('pg', 'Papua New Guinea', 598);
INSERT IGNORE INTO `country` VALUES ('py', 'Paraguay', 600);
INSERT IGNORE INTO `country` VALUES ('pe', 'Peru', 604);
INSERT IGNORE INTO `country` VALUES ('ph', 'Philippines', 608);
INSERT IGNORE INTO `country` VALUES ('pn', 'Pitcairn', 612);
INSERT IGNORE INTO `country` VALUES ('pl', 'Poland', 616);
INSERT IGNORE INTO `country` VALUES ('pt', 'Portugal', 620);
INSERT IGNORE INTO `country` VALUES ('pr', 'Puerto Rico', 630);
INSERT IGNORE INTO `country` VALUES ('qa', 'Qatar', 634);
INSERT IGNORE INTO `country` VALUES ('re', 'Reunion', 638);
INSERT IGNORE INTO `country` VALUES ('ro', 'Romania', 642);
INSERT IGNORE INTO `country` VALUES ('ru', 'Russian Federation', 643);
INSERT IGNORE INTO `country` VALUES ('rw', 'Rwanda', 646);
INSERT IGNORE INTO `country` VALUES ('sh', 'Saint Helena', 654);
INSERT IGNORE INTO `country` VALUES ('kn', 'Saint Kitts and Nevis', 659);
INSERT IGNORE INTO `country` VALUES ('lc', 'Saint Lucia', 662);
INSERT IGNORE INTO `country` VALUES ('pm', 'Saint Pierre and Miquelon', 666);
INSERT IGNORE INTO `country` VALUES ('vc', 'Saint Vincent and the Grenadines', 670);
INSERT IGNORE INTO `country` VALUES ('ws', 'Samoa', 882);
INSERT IGNORE INTO `country` VALUES ('sm', 'San Marino', 674);
INSERT IGNORE INTO `country` VALUES ('st', 'Sao Tome and Principe', 678);
INSERT IGNORE INTO `country` VALUES ('sa', 'Saudi Arabia', 682);
INSERT IGNORE INTO `country` VALUES ('sn', 'Senegal', 686);
INSERT IGNORE INTO `country` VALUES ('rs', 'Serbia', 688);
INSERT IGNORE INTO `country` VALUES ('rs', 'Serbia', 688);
INSERT IGNORE INTO `country` VALUES ('sc', 'Seychelles', 690);
INSERT IGNORE INTO `country` VALUES ('sl', 'Sierra Leone', 694);
INSERT IGNORE INTO `country` VALUES ('sg', 'Singapore', 702);
INSERT IGNORE INTO `country` VALUES ('sk', 'Slovakia', 703);
INSERT IGNORE INTO `country` VALUES ('si', 'Slovenia', 705);
INSERT IGNORE INTO `country` VALUES ('sb', 'Solomon Islands', 90);
INSERT IGNORE INTO `country` VALUES ('so', 'Somalia', 706);
INSERT IGNORE INTO `country` VALUES ('za', 'South Africa', 710);
INSERT IGNORE INTO `country` VALUES ('gs', 'South Georgia and the South Sandwich Islands', 239);
INSERT IGNORE INTO `country` VALUES ('es', 'Spain', 724);
INSERT IGNORE INTO `country` VALUES ('lk', 'Sri Lanka', 144);
INSERT IGNORE INTO `country` VALUES ('sd', 'Sudan', 736);
INSERT IGNORE INTO `country` VALUES ('sr', 'Suriname', 740);
INSERT IGNORE INTO `country` VALUES ('sj', 'Svalbard and Jan Mayen', 744);
INSERT IGNORE INTO `country` VALUES ('sz', 'Swaziland', 748);
INSERT IGNORE INTO `country` VALUES ('se', 'Sweden', 752);
INSERT IGNORE INTO `country` VALUES ('ch', 'Switzerland', 756);
INSERT IGNORE INTO `country` VALUES ('sy', 'Syrian Arab Republic', 760);
INSERT IGNORE INTO `country` VALUES ('tw', 'Taiwan, Province of China', 158);
INSERT IGNORE INTO `country` VALUES ('tj', 'Tajikistan', 762);
INSERT IGNORE INTO `country` VALUES ('tz', 'Tanzania, United Republic of', 834);
INSERT IGNORE INTO `country` VALUES ('th', 'Thailand', 764);
INSERT IGNORE INTO `country` VALUES ('tl', 'Timor-Leste', 626);
INSERT IGNORE INTO `country` VALUES ('tg', 'Togo', 768);
INSERT IGNORE INTO `country` VALUES ('tk', 'Tokelau', 772);
INSERT IGNORE INTO `country` VALUES ('to', 'Tonga', 776);
INSERT IGNORE INTO `country` VALUES ('tt', 'Trinidad and Tobago', 780);
INSERT IGNORE INTO `country` VALUES ('tn', 'Tunisia', 788);
INSERT IGNORE INTO `country` VALUES ('tr', 'Turkey', 792);
INSERT IGNORE INTO `country` VALUES ('tm', 'Turkmenistan', 795);
INSERT IGNORE INTO `country` VALUES ('tc', 'Turks and Caicos Islands', 796);
INSERT IGNORE INTO `country` VALUES ('tv', 'Tuvalu', 798);
INSERT IGNORE INTO `country` VALUES ('ug', 'Uganda', 800);
INSERT IGNORE INTO `country` VALUES ('ua', 'Ukraine', 804);
INSERT IGNORE INTO `country` VALUES ('ae', 'United Arab Emirates', 784);
INSERT IGNORE INTO `country` VALUES ('gb', 'United Kingdom', 826);
INSERT IGNORE INTO `country` VALUES ('us', 'United States', 840);
INSERT IGNORE INTO `country` VALUES ('um', 'United States Minor Outlying Islands', 581);
INSERT IGNORE INTO `country` VALUES ('uy', 'Uruguay', 858);
INSERT IGNORE INTO `country` VALUES ('uz', 'Uzbekistan', 860);
INSERT IGNORE INTO `country` VALUES ('vu', 'Vanuatu', 548);
INSERT IGNORE INTO `country` VALUES ('ve', 'Venezuela', 862);
INSERT IGNORE INTO `country` VALUES ('vn', 'Viet Nam', 704);
INSERT IGNORE INTO `country` VALUES ('vg', 'Virgin Islands, British', 92);
INSERT IGNORE INTO `country` VALUES ('vi', 'Virgin Islands, U.s.', 850);
INSERT IGNORE INTO `country` VALUES ('wf', 'Wallis and Futuna', 876);
INSERT IGNORE INTO `country` VALUES ('eh', 'Western Sahara', 732);
INSERT IGNORE INTO `country` VALUES ('ye', 'Yemen', 887);
INSERT IGNORE INTO `country` VALUES ('zm', 'Zambia', 894);
INSERT IGNORE INTO `country` VALUES ('zw', 'Zimbabwe', 716);


-- --------------------------------------------------------

--
-- Database version
--

UPDATE `server` SET `value` = '' WHERE `name` = 'latest_version' LIMIT 1;
UPDATE `server` SET `value` = '0' WHERE `name` = 'latest_version_idle_time' LIMIT 1;
UPDATE `server` SET `value` = '43' WHERE `name` = 'database_version' LIMIT 1;